[svn] Move rpm install by pass code into functions

diff --git a/trunk/lib/functions b/trunk/lib/functions
--- a/trunk/lib/functions
+++ b/trunk/lib/functions
@@ -167,3 +167,66 @@ set_mirrors() {
         BEST_MIRROR=$1
     fi
 }
+
+install_by_pass() {
+    # Given a list of RPMs ordered by pass, will install them
+    # This is the basic install function provided by rpmstrap,
+    # if you need anything else above and beyond this, you
+    # will have to script it yourself.
+    local RPMS_LIST=$1
+    shift
+    for a in $@
+    do
+        RPMS_LIST=$(echo -e "$RPMS_LIST\n$a")
+    done
+    local rpms_to_get=$(echo "$RPMS_LIST" | sed "s/[[:digit:]]\+://")
+    get_rpms $rpms_to_get
+
+    if [ "$DOWNLOAD_ONLY" = "" ]; then
+        if [ $(id -u) -ne 0 ]; then
+            die "must have root privileges to create chroot"
+        fi
+
+        trace "creating chroot directory"
+        if [ -e "$TARGET" ]; then
+            die "chroot directory $TARGET already exists; aborting"
+        fi
+
+        mkdir -p "$TARGET/var/lib/rpm"
+
+        local passnum=0
+
+        cd $PKG_DIR
+
+        while :; do
+            trace "Installing pass number $passnum..."
+            local pass=$(echo "$RPMS_LIST" | grep "^$passnum:" | sed 's/^[0-9]\+://')
+            if [ -z "$pass" ]; then
+                trace "...nothing left to do."
+                break
+            else
+                set -- $pass
+
+                # make sure each RPM exists
+                for RPM; do
+                    if [ ! -e "$RPM" ]; then
+                        die "cannot find required package $RPM"
+                    fi
+                done
+
+                # rpm insists on having an absolute path to its --root option's argument
+                if ! expr "$TARGET" : "/" >/dev/null 2>&1; then
+                    TARGET="$PWD/$TARGET"
+                fi
+                trace "Installing $* to $TARGET..."
+                if ! rpm --install --root "$TARGET" $@; then
+                    die "command \"rpm --install --root $TARGET $*\"" \
+                    "failed"
+                fi
+            fi
+            passnum=$(( $passnum + 1 ))
+        done
+
+        cd $PWD
+    fi
+}
